"""REST 路由注册表:server.py 统一 include;manifest 聚合各模块端点元数据。

新增 router 模块的接线口就在这里:import 模块 → ALL_ROUTERS 加 router →
ALL_MANIFEST_ENTRIES 拼其 MANIFEST_ENTRIES(/api/* 之外的路由如 downloads 不进 manifest)。
漏接会被 tests/test_manifest.py 防漂移测试逮住。
"""

from app.http import (
    accounts_rest,
    admin_rest,
    cookies_import,
    content_archive_rest,
    cookies_rest,
    downloads,
    dreamina_rest,
    extension_rest,
    interaction_backfill_rest,
    manifest,
    note_comment_rest,
    note_component_reads_rest,
    note_components_rest,
    notes_rest,
    op_images_rest,
    publish_artifacts_rest,
    publish_rest,
    published_notes_rest,
    style_profile_rest,
    system,
    uploads_rest,
    video_assets_rest,
    video_rest,
)

ALL_ROUTERS = [
    system.router,
    manifest.router,
    accounts_rest.router,
    admin_rest.router,
    cookies_import.router,
    content_archive_rest.router,
    cookies_rest.router,
    extension_rest.router,
    publish_rest.router,
    notes_rest.router,
    published_notes_rest.router,
    note_comment_rest.router,
    note_component_reads_rest.router,
    note_components_rest.router,
    interaction_backfill_rest.router,
    op_images_rest.router,
    publish_artifacts_rest.router,
    style_profile_rest.router,
    downloads.router,
    uploads_rest.router,
    video_rest.router,
    video_assets_rest.router,
    dreamina_rest.router,
]

ALL_MANIFEST_ENTRIES = [
    *system.MANIFEST_ENTRIES,
    *manifest.MANIFEST_ENTRIES,
    *accounts_rest.MANIFEST_ENTRIES,
    *admin_rest.MANIFEST_ENTRIES,
    *cookies_import.MANIFEST_ENTRIES,
    *content_archive_rest.MANIFEST_ENTRIES,
    *cookies_rest.MANIFEST_ENTRIES,
    *extension_rest.MANIFEST_ENTRIES,
    *publish_rest.MANIFEST_ENTRIES,
    *notes_rest.MANIFEST_ENTRIES,
    *published_notes_rest.MANIFEST_ENTRIES,
    *note_comment_rest.MANIFEST_ENTRIES,
    *note_component_reads_rest.MANIFEST_ENTRIES,
    *note_components_rest.MANIFEST_ENTRIES,
    *interaction_backfill_rest.MANIFEST_ENTRIES,
    *op_images_rest.MANIFEST_ENTRIES,
    *publish_artifacts_rest.MANIFEST_ENTRIES,
    *style_profile_rest.MANIFEST_ENTRIES,
    *uploads_rest.MANIFEST_ENTRIES,
    *video_rest.MANIFEST_ENTRIES,
    *video_assets_rest.MANIFEST_ENTRIES,
    *dreamina_rest.MANIFEST_ENTRIES,
]
